### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by illuminatibit** [mchangrh/sb.js#5] opened 2022-10-16 13:16 UTC
Syntax error in script: sb.js userscript
await is only valid in async functions and the top level bodies of modules

The script just doesn't work, what should I do?

**Comment by mchangrh** [comment] 2022-10-17 01:21
ah oops, that would be an issue on my end - that was intended for the sb-config userscript

**Comment by illuminatibit** [comment] 2022-10-17 15:47
sb.js userscript loader:

Error running script: sb.js userscript loader
ReferenceError: serverEndpoint is not defined
serverEndpoint is not defined

Which script will work just by installing it?

**Comment by mchangrh** [comment] 2022-10-17 17:56
fixed in https://github.com/mchangrh/sb.js/commit/8e01ba09de32262f2c5d16ff28199df5a24aafe8

**Closed as completed by mchangrh** 2022-10-17 17:56 UTC
